name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - seaborn
  - pandas
  - pip
  - numpy
  - pyarrow
  - jupyter
  - ydata-profiling
  - nbconvert
  - ipywidgets
  - pip:
      - wandb